package flower

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pocka/api.somesim/models"
)

// GetFlowersNameOKCode is the HTTP code returned for type GetFlowersNameOK
const GetFlowersNameOKCode int = 200

/*GetFlowersNameOK 花びら定義

swagger:response getFlowersNameOK
*/
type GetFlowersNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Flower `json:"body,omitempty"`
}

// NewGetFlowersNameOK creates GetFlowersNameOK with default headers values
func NewGetFlowersNameOK() *GetFlowersNameOK {
	return &GetFlowersNameOK{}
}

// WithPayload adds the payload to the get flowers name o k response
func (o *GetFlowersNameOK) WithPayload(payload *models.Flower) *GetFlowersNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get flowers name o k response
func (o *GetFlowersNameOK) SetPayload(payload *models.Flower) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFlowersNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFlowersNameNotFoundCode is the HTTP code returned for type GetFlowersNameNotFound
const GetFlowersNameNotFoundCode int = 404

/*GetFlowersNameNotFound 指定された花びら定義が存在しない

swagger:response getFlowersNameNotFound
*/
type GetFlowersNameNotFound struct {
}

// NewGetFlowersNameNotFound creates GetFlowersNameNotFound with default headers values
func NewGetFlowersNameNotFound() *GetFlowersNameNotFound {
	return &GetFlowersNameNotFound{}
}

// WriteResponse to the client
func (o *GetFlowersNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
