package flower

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostFlowersCreatedCode is the HTTP code returned for type PostFlowersCreated
const PostFlowersCreatedCode int = 201

/*PostFlowersCreated 追加に成功

swagger:response postFlowersCreated
*/
type PostFlowersCreated struct {
}

// NewPostFlowersCreated creates PostFlowersCreated with default headers values
func NewPostFlowersCreated() *PostFlowersCreated {
	return &PostFlowersCreated{}
}

// WriteResponse to the client
func (o *PostFlowersCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// PostFlowersConflictCode is the HTTP code returned for type PostFlowersConflict
const PostFlowersConflictCode int = 409

/*PostFlowersConflict 指定された名前の花びらが既に存在する

swagger:response postFlowersConflict
*/
type PostFlowersConflict struct {
}

// NewPostFlowersConflict creates PostFlowersConflict with default headers values
func NewPostFlowersConflict() *PostFlowersConflict {
	return &PostFlowersConflict{}
}

// WriteResponse to the client
func (o *PostFlowersConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}
