package flower

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/pocka/api.somesim/models"
)

// PutFlowersNameHandlerFunc turns a function with the right signature into a put flowers name handler
type PutFlowersNameHandlerFunc func(PutFlowersNameParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutFlowersNameHandlerFunc) Handle(params PutFlowersNameParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutFlowersNameHandler interface for that can handle valid put flowers name params
type PutFlowersNameHandler interface {
	Handle(PutFlowersNameParams, *models.Principal) middleware.Responder
}

// NewPutFlowersName creates a new http.Handler for the put flowers name operation
func NewPutFlowersName(ctx *middleware.Context, handler PutFlowersNameHandler) *PutFlowersName {
	return &PutFlowersName{Context: ctx, Handler: handler}
}

/*PutFlowersName swagger:route PUT /flowers/{name} Flower putFlowersName

花びら定義を更新

指定した名前の花びら定義を更新する


*/
type PutFlowersName struct {
	Context *middleware.Context
	Handler PutFlowersNameHandler
}

func (o *PutFlowersName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutFlowersNameParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
