package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTokensAccessTokenOKCode is the HTTP code returned for type GetTokensAccessTokenOK
const GetTokensAccessTokenOKCode int = 200

/*GetTokensAccessTokenOK アクセストークン

swagger:response getTokensAccessTokenOK
*/
type GetTokensAccessTokenOK struct {

	/*アクセストークン(JWT)
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetTokensAccessTokenOK creates GetTokensAccessTokenOK with default headers values
func NewGetTokensAccessTokenOK() *GetTokensAccessTokenOK {
	return &GetTokensAccessTokenOK{}
}

// WithPayload adds the payload to the get tokens access token o k response
func (o *GetTokensAccessTokenOK) WithPayload(payload string) *GetTokensAccessTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tokens access token o k response
func (o *GetTokensAccessTokenOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokensAccessTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
