package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetTokensAccessTokenHandlerFunc turns a function with the right signature into a get tokens access token handler
type GetTokensAccessTokenHandlerFunc func(GetTokensAccessTokenParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTokensAccessTokenHandlerFunc) Handle(params GetTokensAccessTokenParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTokensAccessTokenHandler interface for that can handle valid get tokens access token params
type GetTokensAccessTokenHandler interface {
	Handle(GetTokensAccessTokenParams, interface{}) middleware.Responder
}

// NewGetTokensAccessToken creates a new http.Handler for the get tokens access token operation
func NewGetTokensAccessToken(ctx *middleware.Context, handler GetTokensAccessTokenHandler) *GetTokensAccessToken {
	return &GetTokensAccessToken{Context: ctx, Handler: handler}
}

/*GetTokensAccessToken swagger:route GET /tokens/access_token User getTokensAccessToken

アクセストークンを取得する

リフレッシュトークンを用いてアクセストークンを取得する


*/
type GetTokensAccessToken struct {
	Context *middleware.Context
	Handler GetTokensAccessTokenHandler
}

func (o *GetTokensAccessToken) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetTokensAccessTokenParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
