package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTokensOKCode is the HTTP code returned for type GetTokensOK
const GetTokensOKCode int = 200

/*GetTokensOK アクセストークンとリフレッシュトークン

swagger:response getTokensOK
*/
type GetTokensOK struct {

	/*
	  In: Body
	*/
	Payload GetTokensOKBody `json:"body,omitempty"`
}

// NewGetTokensOK creates GetTokensOK with default headers values
func NewGetTokensOK() *GetTokensOK {
	return &GetTokensOK{}
}

// WithPayload adds the payload to the get tokens o k response
func (o *GetTokensOK) WithPayload(payload GetTokensOKBody) *GetTokensOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tokens o k response
func (o *GetTokensOK) SetPayload(payload GetTokensOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokensOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
