package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Flower 花びら定義
// swagger:model Flower
type Flower struct {

	// 青色の値(%)
	Blue int64 `json:"blue,omitempty"`

	// 花びらの所属するカテゴリ
	Category string `json:"category,omitempty"`

	// 緑色の値(%)
	Green int64 `json:"green,omitempty"`

	// 花びらの名前
	Name string `json:"name,omitempty"`

	// 赤色の値(%)
	Red int64 `json:"red,omitempty"`
}

// Validate validates this flower
func (m *Flower) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
