package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ImageSet 装備画像セット(ベース画像とマスク画像のペア)
// swagger:model ImageSet
type ImageSet struct {

	// Base64エンコードされたベース画像
	BaseImage string `json:"base_image,omitempty"`

	// Base64エンコードされたマスク画像
	MaskImage string `json:"mask_image,omitempty"`

	// 装備画像セットの名前
	Name string `json:"name,omitempty"`
}

// Validate validates this image set
func (m *ImageSet) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
