package internal_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetDocsParams creates a new GetDocsParams object
// with the default values initialized.
func NewGetDocsParams() GetDocsParams {
	var ()
	return GetDocsParams{}
}

// GetDocsParams contains all the bound params for the get docs operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetDocs
type GetDocsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetDocsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
