package internal_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDocsSwaggerYmlOKCode is the HTTP code returned for type GetDocsSwaggerYmlOK
const GetDocsSwaggerYmlOKCode int = 200

/*GetDocsSwaggerYmlOK スキーマ(Swagger)


swagger:response getDocsSwaggerYmlOK
*/
type GetDocsSwaggerYmlOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetDocsSwaggerYmlOK creates GetDocsSwaggerYmlOK with default headers values
func NewGetDocsSwaggerYmlOK() *GetDocsSwaggerYmlOK {
	return &GetDocsSwaggerYmlOK{}
}

// WithPayload adds the payload to the get docs swagger yml o k response
func (o *GetDocsSwaggerYmlOK) WithPayload(payload string) *GetDocsSwaggerYmlOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get docs swagger yml o k response
func (o *GetDocsSwaggerYmlOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDocsSwaggerYmlOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDocsSwaggerYmlNotFoundCode is the HTTP code returned for type GetDocsSwaggerYmlNotFound
const GetDocsSwaggerYmlNotFoundCode int = 404

/*GetDocsSwaggerYmlNotFound ファイルが存在しない


swagger:response getDocsSwaggerYmlNotFound
*/
type GetDocsSwaggerYmlNotFound struct {
}

// NewGetDocsSwaggerYmlNotFound creates GetDocsSwaggerYmlNotFound with default headers values
func NewGetDocsSwaggerYmlNotFound() *GetDocsSwaggerYmlNotFound {
	return &GetDocsSwaggerYmlNotFound{}
}

// WriteResponse to the client
func (o *GetDocsSwaggerYmlNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
