package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pocka/api.somesim/models"
)

// GetItemsNameImagesImageNameOKCode is the HTTP code returned for type GetItemsNameImagesImageNameOK
const GetItemsNameImagesImageNameOKCode int = 200

/*GetItemsNameImagesImageNameOK 画像セット


swagger:response getItemsNameImagesImageNameOK
*/
type GetItemsNameImagesImageNameOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ImageSet `json:"body,omitempty"`
}

// NewGetItemsNameImagesImageNameOK creates GetItemsNameImagesImageNameOK with default headers values
func NewGetItemsNameImagesImageNameOK() *GetItemsNameImagesImageNameOK {
	return &GetItemsNameImagesImageNameOK{}
}

// WithPayload adds the payload to the get items name images image name o k response
func (o *GetItemsNameImagesImageNameOK) WithPayload(payload []*models.ImageSet) *GetItemsNameImagesImageNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get items name images image name o k response
func (o *GetItemsNameImagesImageNameOK) SetPayload(payload []*models.ImageSet) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemsNameImagesImageNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.ImageSet, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetItemsNameImagesImageNameNotFoundCode is the HTTP code returned for type GetItemsNameImagesImageNameNotFound
const GetItemsNameImagesImageNameNotFoundCode int = 404

/*GetItemsNameImagesImageNameNotFound 指定された名前の画像セットが存在しない

swagger:response getItemsNameImagesImageNameNotFound
*/
type GetItemsNameImagesImageNameNotFound struct {
}

// NewGetItemsNameImagesImageNameNotFound creates GetItemsNameImagesImageNameNotFound with default headers values
func NewGetItemsNameImagesImageNameNotFound() *GetItemsNameImagesImageNameNotFound {
	return &GetItemsNameImagesImageNameNotFound{}
}

// WriteResponse to the client
func (o *GetItemsNameImagesImageNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
