package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pocka/api.somesim/models"
)

// GetItemsNameImagesOKCode is the HTTP code returned for type GetItemsNameImagesOK
const GetItemsNameImagesOKCode int = 200

/*GetItemsNameImagesOK その装備に登録されている全ての染色用画像セット


swagger:response getItemsNameImagesOK
*/
type GetItemsNameImagesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ImageSet `json:"body,omitempty"`
}

// NewGetItemsNameImagesOK creates GetItemsNameImagesOK with default headers values
func NewGetItemsNameImagesOK() *GetItemsNameImagesOK {
	return &GetItemsNameImagesOK{}
}

// WithPayload adds the payload to the get items name images o k response
func (o *GetItemsNameImagesOK) WithPayload(payload []*models.ImageSet) *GetItemsNameImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get items name images o k response
func (o *GetItemsNameImagesOK) SetPayload(payload []*models.ImageSet) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemsNameImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.ImageSet, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
