package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostItemsCreatedCode is the HTTP code returned for type PostItemsCreated
const PostItemsCreatedCode int = 201

/*PostItemsCreated 作成に成功

swagger:response postItemsCreated
*/
type PostItemsCreated struct {
}

// NewPostItemsCreated creates PostItemsCreated with default headers values
func NewPostItemsCreated() *PostItemsCreated {
	return &PostItemsCreated{}
}

// WriteResponse to the client
func (o *PostItemsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// PostItemsConflictCode is the HTTP code returned for type PostItemsConflict
const PostItemsConflictCode int = 409

/*PostItemsConflict 同じ名前の装備情報が既に存在する

swagger:response postItemsConflict
*/
type PostItemsConflict struct {
}

// NewPostItemsConflict creates PostItemsConflict with default headers values
func NewPostItemsConflict() *PostItemsConflict {
	return &PostItemsConflict{}
}

// WriteResponse to the client
func (o *PostItemsConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}
