package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostItemsNameImagesCreatedCode is the HTTP code returned for type PostItemsNameImagesCreated
const PostItemsNameImagesCreatedCode int = 201

/*PostItemsNameImagesCreated 追加に成功した

swagger:response postItemsNameImagesCreated
*/
type PostItemsNameImagesCreated struct {
}

// NewPostItemsNameImagesCreated creates PostItemsNameImagesCreated with default headers values
func NewPostItemsNameImagesCreated() *PostItemsNameImagesCreated {
	return &PostItemsNameImagesCreated{}
}

// WriteResponse to the client
func (o *PostItemsNameImagesCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
}

// PostItemsNameImagesConflictCode is the HTTP code returned for type PostItemsNameImagesConflict
const PostItemsNameImagesConflictCode int = 409

/*PostItemsNameImagesConflict 指定された名前の装備画像セットが既に存在する

swagger:response postItemsNameImagesConflict
*/
type PostItemsNameImagesConflict struct {
}

// NewPostItemsNameImagesConflict creates PostItemsNameImagesConflict with default headers values
func NewPostItemsNameImagesConflict() *PostItemsNameImagesConflict {
	return &PostItemsNameImagesConflict{}
}

// WriteResponse to the client
func (o *PostItemsNameImagesConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
}
