package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/pocka/api.somesim/models"
)

// PutItemsNameImagesImageNameHandlerFunc turns a function with the right signature into a put items name images image name handler
type PutItemsNameImagesImageNameHandlerFunc func(PutItemsNameImagesImageNameParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PutItemsNameImagesImageNameHandlerFunc) Handle(params PutItemsNameImagesImageNameParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PutItemsNameImagesImageNameHandler interface for that can handle valid put items name images image name params
type PutItemsNameImagesImageNameHandler interface {
	Handle(PutItemsNameImagesImageNameParams, *models.Principal) middleware.Responder
}

// NewPutItemsNameImagesImageName creates a new http.Handler for the put items name images image name operation
func NewPutItemsNameImagesImageName(ctx *middleware.Context, handler PutItemsNameImagesImageNameHandler) *PutItemsNameImagesImageName {
	return &PutItemsNameImagesImageName{Context: ctx, Handler: handler}
}

/*PutItemsNameImagesImageName swagger:route PUT /items/{name}/images/{image_name} Item putItemsNameImagesImageName

染色用画像を更新

染色用画像を更新する


*/
type PutItemsNameImagesImageName struct {
	Context *middleware.Context
	Handler PutItemsNameImagesImageNameHandler
}

func (o *PutItemsNameImagesImageName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutItemsNameImagesImageNameParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
