package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutItemsNameHandlerFunc turns a function with the right signature into a put items name handler
type PutItemsNameHandlerFunc func(PutItemsNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutItemsNameHandlerFunc) Handle(params PutItemsNameParams) middleware.Responder {
	return fn(params)
}

// PutItemsNameHandler interface for that can handle valid put items name params
type PutItemsNameHandler interface {
	Handle(PutItemsNameParams) middleware.Responder
}

// NewPutItemsName creates a new http.Handler for the put items name operation
func NewPutItemsName(ctx *middleware.Context, handler PutItemsNameHandler) *PutItemsName {
	return &PutItemsName{Context: ctx, Handler: handler}
}

/*PutItemsName swagger:route PUT /items/{name} Item putItemsName

装備情報を更新

指定された名前の装備情報を更新する


*/
type PutItemsName struct {
	Context *middleware.Context
	Handler PutItemsNameHandler
}

func (o *PutItemsName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutItemsNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
