package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutItemsNameImagesImageNameNoContentCode is the HTTP code returned for type PutItemsNameImagesImageNameNoContent
const PutItemsNameImagesImageNameNoContentCode int = 204

/*PutItemsNameImagesImageNameNoContent 更新に成功

swagger:response putItemsNameImagesImageNameNoContent
*/
type PutItemsNameImagesImageNameNoContent struct {
}

// NewPutItemsNameImagesImageNameNoContent creates PutItemsNameImagesImageNameNoContent with default headers values
func NewPutItemsNameImagesImageNameNoContent() *PutItemsNameImagesImageNameNoContent {
	return &PutItemsNameImagesImageNameNoContent{}
}

// WriteResponse to the client
func (o *PutItemsNameImagesImageNameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// PutItemsNameImagesImageNameNotFoundCode is the HTTP code returned for type PutItemsNameImagesImageNameNotFound
const PutItemsNameImagesImageNameNotFoundCode int = 404

/*PutItemsNameImagesImageNameNotFound 指定された名前の染色用画像が存在しない

swagger:response putItemsNameImagesImageNameNotFound
*/
type PutItemsNameImagesImageNameNotFound struct {
}

// NewPutItemsNameImagesImageNameNotFound creates PutItemsNameImagesImageNameNotFound with default headers values
func NewPutItemsNameImagesImageNameNotFound() *PutItemsNameImagesImageNameNotFound {
	return &PutItemsNameImagesImageNameNotFound{}
}

// WriteResponse to the client
func (o *PutItemsNameImagesImageNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
