package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PutItemsNameNoContentCode is the HTTP code returned for type PutItemsNameNoContent
const PutItemsNameNoContentCode int = 204

/*PutItemsNameNoContent 更新に成功した

swagger:response putItemsNameNoContent
*/
type PutItemsNameNoContent struct {
}

// NewPutItemsNameNoContent creates PutItemsNameNoContent with default headers values
func NewPutItemsNameNoContent() *PutItemsNameNoContent {
	return &PutItemsNameNoContent{}
}

// WriteResponse to the client
func (o *PutItemsNameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

// PutItemsNameNotFoundCode is the HTTP code returned for type PutItemsNameNotFound
const PutItemsNameNotFoundCode int = 404

/*PutItemsNameNotFound 指定された名前の装備情報が存在しない

swagger:response putItemsNameNotFound
*/
type PutItemsNameNotFound struct {
}

// NewPutItemsNameNotFound creates PutItemsNameNotFound with default headers values
func NewPutItemsNameNotFound() *PutItemsNameNotFound {
	return &PutItemsNameNotFound{}
}

// WriteResponse to the client
func (o *PutItemsNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
