package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutItemsNameImagesImageNameHandlerFunc turns a function with the right signature into a put items name images image name handler
type PutItemsNameImagesImageNameHandlerFunc func(PutItemsNameImagesImageNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutItemsNameImagesImageNameHandlerFunc) Handle(params PutItemsNameImagesImageNameParams) middleware.Responder {
	return fn(params)
}

// PutItemsNameImagesImageNameHandler interface for that can handle valid put items name images image name params
type PutItemsNameImagesImageNameHandler interface {
	Handle(PutItemsNameImagesImageNameParams) middleware.Responder
}

// NewPutItemsNameImagesImageName creates a new http.Handler for the put items name images image name operation
func NewPutItemsNameImagesImageName(ctx *middleware.Context, handler PutItemsNameImagesImageNameHandler) *PutItemsNameImagesImageName {
	return &PutItemsNameImagesImageName{Context: ctx, Handler: handler}
}

/*PutItemsNameImagesImageName swagger:route PUT /items/{name}/images/{image_name} Item putItemsNameImagesImageName

染色用画像を更新

染色用画像を更新する


*/
type PutItemsNameImagesImageName struct {
	Context *middleware.Context
	Handler PutItemsNameImagesImageNameHandler
}

func (o *PutItemsNameImagesImageName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutItemsNameImagesImageNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
